### ISSUE TITLE
OutOfMemoryError: CUDA out of memory [Google Collab]

### ISSUE THREAD

**Issue by AshishKumarJena** [huggingface/autotrain-advanced#252]
Can anyone help me with this?
![Screenshot 2023-09-04 034737](https://github.com/huggingface/autotrain-advanced/assets/59320292/2af05ae9-2dba-4950-b39b-d8660102867f)

**Comment by UmarIgan** [comment]
You might not have enough gpu for training, try to update model parameters for it to work on less memory, here is my parameters that works on colab T4 GPU: 
```
learning_rate = 5e-06 
num_steps = 300 
batch_size = 1 
gradient_accumulation = 4 
resolution = 1024 
use_8bit_adam = True 
use_xformers = True
use_fp16 = True
train_text_encoder = False 
gradient_checkpointing = True
```
Once I run into this issue I tried to use lighter model and secondly  deleted runtime  on colab and rerun all codes, this will help you to remove cached data.

**Comment by sankeerth-bussa** [comment]
Here is the update code. I have added lines to delete the unused variables so that it free up GPU

`# Inference
# this is the inference code that you can use after you have trained your model
# Unhide code below and change prj_path to your repo or local path (e.g. my_dreambooth_project)
#
#
#
from diffusers import DiffusionPipeline, StableDiffusionXLImg2ImgPipeline
import torch

prj_path = "/project"
model = "stabilityai/stable-diffusion-xl-base-1.0"
pipe = DiffusionPipeline.from_pretrained(
    model,
    torch_dtype=torch.float16,
)
pipe.to("cuda")
pipe.load_lora_weights(prj_path, weight_name="pytorch_lora_weights.safetensors")


prompt = "Image of SKS dog"

seed = 42
generator = torch.Generator("cuda").manual_seed(seed)
image = pipe(prompt=prompt, generator=generator).images[0]

del pipe

refiner = StableDiffusionXLImg2ImgPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-refiner-1.0",
    torch_dtype=torch.float16,
)
refiner.to("cuda")

image = refiner(prompt=prompt, generator=generator, image=image).images[0]
del generator
del refiner
image.save(f"generate_image.png")`

**Comment by thesamyadeep** [comment]
will check this updated code ASAP.

**Comment by thesamyadeep** [comment]
managed to get 1 image output. do I need to run this every time to generate 1 image?
or there is a shorter code to run after this to generate more images?

**Comment by UmarIgan** [comment]
there must num_images_per_prompt arg in pipe, with setting up that you can produce more images
here is an baseline:
https://colab.research.google.com/github/UmarIgan/Machine-Learning/blob/master/Stable_Diffisuon_Fine_Tuning_With_Dreambooth_Autotrain.ipynb

**Comment by Jaykumar-coder** [comment]
This worked. Thanks for the code.
