### ISSUE TITLE
AutoTrain not adding job

### ISSUE THREAD

**Issue by lhallee** [huggingface/autotrain-advanced#342]
Autotrain adds job fine with manual settings. With Autotrain parameters set it gives an error. Even when I switch my Autotrain advanced space to GPU runtime it won't add the job (no error message for this scenario).

This works
![image](https://github.com/huggingface/autotrain-advanced/assets/72926928/f769c34d-7d0e-4a81-a381-5d6db6ec88d1)

This does not
![image](https://github.com/huggingface/autotrain-advanced/assets/72926928/415884d5-5b07-471c-80bd-6dfc4a7a611e)

![image](https://github.com/huggingface/autotrain-advanced/assets/72926928/aa17e569-8e4d-42a7-9b5a-6d9179cf89de)

**Comment by abhishekkrthakur** [comment]
AutoTrain parameter choice has been deprecated to have more control and transparency on parameters used. It will soon be removed.

**Comment by lhallee** [comment]
AutoTrain is very attractive due to the multiple model options. Will this be kept? Without that I don't see a reason to use it instead of HF trainer.

**Comment by abhishekkrthakur** [comment]
Parameter search will still remain in tabular task - powered by optuna. 
LLM, Dreambooth, etc - users need to provide their own parameters. We will also be providing pre-made params. For example, a set of params that have proven to work well with zephyr model.
You will always be able to train multiple models at the same time.
The changes make everything more transparent to the end user and also reduces the cost to a fraction of what it was earlier since now you can chose which hardware you want to train on.

**Comment by lhallee** [comment]
That's amazing. Thanks for the info!
